### PR TITLE
Update BoringSSL to 2023-08-28.

### PR DESCRIPTION
**Pull request by martijneken**
Fixes build warning-as-error:
```
external/boringssl/src/crypto/x509/t_x509.c:326:18: error: variable 'l' set but not used [-Werror,-Wunused-but-set-variable]
    int ret = 0, l, i;
                 ^
```

### CODE REVIEW

**Comment by martijneken** [comment]
- macOS build failures are known issue #384
- cargo-raze failure is being worked on in #390

**Comment by martijneken** [comment]
Friendly ping @PiotrSikora

**Comment by PiotrSikora** [comment]
LGTM, but those should be 2 separate PRs.

**Comment by PiotrSikora** [comment]
> Or if you're talking about the buildifier fix, that was a presubmit identified issue and fixing it is trivial and safe.

This. I agree that it's trivial and safe, but there is no need to bundle those 2 unrelated changes into a single PR.

**Comment by martijneken** [comment]
https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/394 for the BUILD fix

**Review by PiotrSikora — APPROVED** [review]
LGTM, although the fact that we're updating to a version from 8 months ago is a bit questionable.

**Comment by PiotrSikora** [comment]
@martijneken sorry, I keep forgetting that for some reason GitHub decides to use my old `@google.com` email address in UI-triggered merge commits... Could you rebase this on top of `master` and drop my merge commit? Thanks!

**Comment by martijneken** [comment]
@PiotrSikora I'm confused why your review is not considered a sufficient Code Owner review. Maybe because you added a merge commit? BTW this triggered a CLA check issue -- are you able to resolve that?

**Comment by PiotrSikora** [comment]
> @PiotrSikora I'm confused why your review is not considered a sufficient Code Owner review. Maybe because you added a merge commit?

That's not it, see: https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/392#issuecomment-2081956690

> BTW this triggered a CLA check issue -- are you able to resolve that?

Done... But could you merge the `master` branch to enable merge?

**Review by mpwarres — APPROVED** [review]
